apiVersion: v1
kind: Secret
metadata:
  name: azure-voting-app-secret
  labels:
    app: azure-voting-app
type: Opaque
data:
  MYSQL_USER: ZGJ1c2Vy
  MYSQL_PASSWORD: UGFzc3dvcmQxMg==
  MYSQL_DATABASE: YXp1cmV2b3Rl
  MYSQL_HOST: YXp1cmUtdm90aW5nLWFwcC1iYWNrCg==
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQxMg==
