apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-party-clippy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-party-clippy
  template:
    metadata:
      labels:
        app: aci-party-clippy
    spec:
      containers:
      - name: aci-party-clippy
        image: r.j3ss.co/party-clippy
        tty: true
        command: ["party-clippy"]
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
